services:
  - type: web
    name: push-notification-server
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
